#!/bin/bash

# This is a script that will check the existance of configuration files and copy them to a central location

echo running migrate!

DESTINATION="$HOME/google\ drive/calvins_dev_environment"
SOURCE=""

files=( ".vimrc"
	".bash_profile" 
	".bashrc"
	".tmux.conf" 
	".git_ignore" 
	"alias_list" 
	".gitingore_global")

# copy a file from source to destination
# source is arg1
# destination is arg2
copy (){
	if [ -f "$1" ]
	then
		cp $1 ${DESTINATION}/$1
		echo copied $1
	else
		echo "$1 does not exist"
	fi
}

# change to $HOME
cd $HOME

# used to iterate over the array of files to call the copy function
# for now only cat the file
for i in "${files[@]}"
do
	copy $i
done

# change to previous directory
cd -

cd $HOME/google\ drive/calvins_dev_environment

git status

git add .

git commit -m ${date}

# change the to previous directory
cd -
